---
fixtures:
  repositories:
    apache:
      repo: https://github.com/simp/pupmod-simp-apache
      branch: 5.X
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      branch: 5.X
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      branch: 5.X
    compliance: https://github.com/simp/pupmod-simp-compliance_markup
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: 5.X
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
      branch: 5.X
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      branch: 5.X
    rsync:
      repo: https://github.com/simp/pupmod-simp-rsync
      branch: 5.X
    rsyslog:
      repo: https://github.com/simp/pupmod-simp-rsyslog
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    ganglia: "#{source_dir}"
